language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: qhaSq8poRacuua0P3NVz5IKjOd9/rUY/L65UD6QOROraJcBpWVEs2LVPZyOg4tT3jZEXGClfcsAAcvrncbVpM4I2By103i03Ln29q9mlLoszbtl5S4wvaCV1iRamZwmY0aOTjnWTPgaVpS6zBNZu+xkmD4ZikBLJy3tmWNeeDGs=
  - secure: CclweOPOT7S5Cff0VKbYfFqn4OuWwa4gHpKEyDuvWhHHcImOC9FQxmhbjqB09mPDLk/z7DroiZt9IqLfESHv3zzzkIcFsU2LuLAdEFtl+JLuZWDH+YCw1QNXFnndmcNnUjsO2vglhoohSK6MJpAupB16VbjG+4bP8Ze4gw1VHbs=
  - secure: GAAsKiajjRtG3Bnddal39gghasWIHzoABvaoMfykNdAjDTo9M4Qa4NsJbtuCHEWL1yZerAk4OfGWcbJ3eMVAUwntibG5K52GLW5mcfTGyt9JfMoHZ+sgakVRCu3cl0U9ag5QIPir/zVfVGizS7BrONk4EhLuzO7oXh5MEjR2Ni8=
notifications:
  slack:
    secure: KMR1DhbbKNz4iUfrLCVAfw7z++rLALYAzqWfj2lVA3h5GsW0P3UMzIQ0+/gbhlWH6MWnRtMirJSOfljuUlAUuLoqjGRxZFJwOc+ozeBfo0wTJjVTq9ul0QSlvaO62CdWrU8VAMKK1TZt+/C+ARcQjyVrHFiAXJkwt+Y7iJzdfAo=
