src/wadl/cbd-devguide.wadl:
    title: Rackspace Cloud Big Data Developer Guide v1
    output_directory: rst/dev-guide/cloud-bigdata-v1/api-operations
    
src/wadl/cbd-devguide-2.wadl:
    title: Rackspace Cloud Big Data Developer Guide v2
    output_directory: rst/dev-guide/cloud-bigdata-v2/api-operations   